# Generated by Django 4.2.1 on 2023-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_chapter_slug_alter_course_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
